ENH: added faq page
pythonindia/inpycon2024 pull request #24
Opened 2024-04-29 17:14 UTC by Schefflera-Arboricola

closes https://github.com/pythonindia/inpycon2024/issues/18

2024-04-30 07:53 UTC, anistark requested changes

2024-04-30 07:53 UTC, anistark commented on src/_pages-content/faq.md
> +No, you do not need a ticket for Devsprints. Devsprints are open to all participants and is free to attend.
We don't know this yet. Better to skip this for now or write TBD something.

2024-04-30 07:53 UTC, anistark commented on src/_pages-content/faq.md
> +No, there won’t be any spot registrations available at the conference venue.
Yes there might be spot registrations as discussed on last call. Please refer to meeting notes.

2024-04-30 07:53 UTC, anistark commented on src/_pages-content/faq.md
> +5. **Sponsor stalls:** Sponsor stalls are where you can meet companies supporting the conference. These companies use Python and are looking for Python developers. You can visit their stalls to get t
Do we call them `stalls` or `booths` ?

2024-04-30 17:20 UTC, Schefflera-Arboricola commented
@anistark thanks for the reviews. 
I've updated all the links as well and I think it's ready now. Please let me know if anything else needs to be added/edited.

> Do we call them `stalls` or `booths` ?

idk, Please let me know.

Thank you :)

2024-05-02 06:13 UTC, bhansa commented on src/_pages-content/faq.md
> +5. **Sponsor stalls:** Sponsor stalls are where you can meet companies supporting the conference. These companies use Python and are looking for Python developers. You can visit their stalls to get t
booth is better.

2024-05-02 11:56 UTC, anistark requested changes

2024-05-02 11:56 UTC, anistark commented on src/_pages-content/faq.md
> +Check out the [Speaker best practices](https://github.com/pythonindia/junction/wiki/Speaker-best-practices) and the [PyCon 2023's Guide to Speaking](https://in.pycon.org/blog/2023/guide-to-speaking.h
Add only 1 link. This should ideally by on navigator but for now junction link is enough. If there's something missing in that content-wise, that can be added from blog link.

2024-05-02 11:56 UTC, anistark commented on src/_pages-content/faq.md
> +Yes, there might be some limited number of spot registrations available at the conference venue.
This is decided now. There's will be a few limited number of on-spot registrations on first-come-first basis. But the goodies are subject to availability.

2024-05-03 20:07 UTC, anistark approved these changes

2024-05-09 19:18 UTC, Schefflera-Arboricola commented
-just a gentle reminder

Thx!

2024-05-10 05:27 UTC, merged